# Generated by Django 5.2 on 2025-04-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejadorEEGFile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eegfile',
            name='gcs_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
